import "./handlers/oracle";
import "./handlers/poll";
import "./handlers/factory";
import "./handlers/amm-trades";
import "./handlers/amm-liquidity";
import "./handlers/amm-resolution";
import "./handlers/parimutuel";
import "./handlers/disputes";
import "./handlers/referral";
import "./handlers/campaign";
// import "./handlers/launchpad";
